// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zlNmR3x_4eUD5Kgkjpyng0nfB7LjXY0',
    appId: '1:966907468865:web:7a4d7a3908bfdb552fbac0',
    messagingSenderId: '966907468865',
    projectId: 'mobileqr-26132',
    authDomain: 'mobileqr-26132.firebaseapp.com',
    storageBucket: 'mobileqr-26132.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAs6906KyaicxxgUJkzrc8ue8gn4Dp5BQ',
    appId: '1:966907468865:android:3df23517ab29fda92fbac0',
    messagingSenderId: '966907468865',
    projectId: 'mobileqr-26132',
    storageBucket: 'mobileqr-26132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZDJH4B0th8LJxo_zlPi0TCUVFH5DWF4',
    appId: '1:966907468865:ios:00edbbb9d289a4c42fbac0',
    messagingSenderId: '966907468865',
    projectId: 'mobileqr-26132',
    storageBucket: 'mobileqr-26132.firebasestorage.app',
    iosBundleId: 'com.example.booq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZDJH4B0th8LJxo_zlPi0TCUVFH5DWF4',
    appId: '1:966907468865:ios:00edbbb9d289a4c42fbac0',
    messagingSenderId: '966907468865',
    projectId: 'mobileqr-26132',
    storageBucket: 'mobileqr-26132.firebasestorage.app',
    iosBundleId: 'com.example.booq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-zlNmR3x_4eUD5Kgkjpyng0nfB7LjXY0',
    appId: '1:966907468865:web:c221317a39d329092fbac0',
    messagingSenderId: '966907468865',
    projectId: 'mobileqr-26132',
    authDomain: 'mobileqr-26132.firebaseapp.com',
    storageBucket: 'mobileqr-26132.firebasestorage.app',
  );
}
